enum NewsCategories {
  arts = 'arts',
  automobiles = 'automobiles',
  books_review = 'books/review',
  business = 'business',
  fashion = 'fashion',
  food = 'food',
  health = 'health',
  home = 'home',
  movies = 'movies',
  politics = 'politics',
  realestate = 'realestate',
  science = 'science',
  sports = 'sports',
  technology = 'technology',
  travel = 'travel',
  world = 'world',
}
